version: "3.8"

services:
  ping:
    build:
      context: ./ping
      dockerfile: Dockerfile
    depends_on:
      - registry
      - message-broker
      - gateway
    networks:
      - isolated_network

  pong:
    build:
      context: ./pong
      dockerfile: Dockerfile
    depends_on:
      - registry
      - message-broker
      - gateway
    networks:
      - isolated_network
  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    container_name: registry
    ports:
      - "8080:8080"

networks:
  isolated_network:
    driver: bridge
