version: "3.8"

services:
  ping:
    build:
      context: ./ping
      dockerfile: Dockerfile
    depends_on:
      - registry
      - message-broker
      - gateway

  pong:
    build:
      context: ./pong
      dockerfile: Dockerfile
    depends_on:
      - registry
      - message-broker
      - gateway
  message-broker:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - registry
  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
