version: "3.8"

services:
  ping:
    build:
      context: ./PING
      dockerfile: Dockerfile-ping
    container_name: server-ping
    ports:
      - "4567:4567"

  pong:
    build:
      context: ./PONG
      dockerfile: Dockerfile-pong
    container_name: pong
    ports:
      - "5372:5372"
