version: "3.8"

services:
  ping:
    build:
      context: ./ping
      dockerfile: Dockerfile
    depends_on:
      - registry
      - message-broker
      - gateway
    networks:
      - isolated_network

  pong:
    build:
      context: ./pong
      dockerfile: Dockerfile
    depends_on:
      - registry
      - message-broker
      - gateway
    networks:
      - isolated_network
  message-broker:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - registry
  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

networks:
  isolated_network:
    driver: bridge
